### ISSUE TITLE
move to servo orga

### ISSUE THREAD

**Issue by paulrouget** [servo/homebrew-servo#3]
I'd like to move this repo under `servo/homebrew-servo`.

To get there, we need https://github.com/servo/servo/pull/9643 and a proper review of this formula.

**Comment by paulrouget** [comment]
@larsbergstrom you think you could look at this or point this to the right person?

**Comment by larsbergstrom** [comment]
I'm probably the right person :-)

Does this script work without `autoconf2.13` installed? For our mac builds, which have to be set up from scratch, that's the other thing we need to install:
https://github.com/servo/saltfs/blob/master/servo-dependencies.sls

Also, there's a nasty bit where you have to make sure to install autoconf first or autoconf2.13 will get brew link'd and then the link for autoconf will fail and there will be a bunch of missing packages.

Thanks for doing this work - it's super exciting!

**Comment by larsbergstrom** [comment]
Also, should we consider providing a prebuilt binary? I happened to run across this today:
http://octavore.com/posts/2016/02/15/distributing-go-apps-os-x

I'm not sure on that bit yet, though :-) Might make it TOO easy to install Servo! But, it'll save a huge amount of pain, especially for people who want the release build.

**Comment by paulrouget** [comment]
> Also, should we consider providing a prebuilt binary?

We have nightly builds?
We could provide both.

**Comment by paulrouget** [comment]
> Does this script work without autoconf2.13 installed?

Apparently it does.

I stripped down my system as much as I could.

No autoconf/automake/autoheader/cmake/… and it works.

**Comment by larsbergstrom** [comment]
We don't have nightly builds yet, but we certainly could :-) Right now, it's just Android nightlies, but it's pretty easy to create a buildbot (or Travis) job that would build and upload them every night.

Did you also blow away the `target/` directory? I thought that `autoconf2.13` was required in order to build SpiderMonkey. CC @jdm

**Comment by jdm** [comment]
mozjs includes a configure script, so maybe autoconf2.13 isn't necessary there?

**Comment by paulrouget** [comment]
> We don't have nightly builds yet, but we certainly could :-) Right now, it's just Android nightlies, but it's pretty easy to create a buildbot (or Travis) job that would build and upload them every night.

Right. Servo probably needs the equivalent of `make install`. Maybe with `cargo install`.

> Did you also blow away the target/ directory?

Yes. Why not?

Today, I just copy the binary, `resources` and `deps`, this is apparently enough.

**Comment by larsbergstrom** [comment]
Great, thanks! Let's move this into the Servo organization :-) If you make me a co-owner of the repo, I can do the necessary button-pressing.

**Comment by paulrouget** [comment]
> Great, thanks! Let's move this into the Servo organization

Done.
