### ISSUE TITLE
setuptools for python is missing

### ISSUE THREAD

**Issue by mattkanwisher** [servo/homebrew-servo#8]
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/servo20160226-37899-1bkn380/_vedir --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/hyper/Library/Logs/Homebrew/servo/01.python:
python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(**file**).read()
  .replace('\r\n', '\n'), **file**, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/servo20160226-37899-1bkn380/_vedir
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

**Comment by mattkanwisher** [comment]
https://github.com/Homebrew/homebrew-python/issues/216 fixed it

**Comment by paulrouget** [comment]
what did you do exactly?

Do we need to install `setuptools` the way `virtualenv` is installed?
